### ISSUE TITLE
添加新功能

### ISSUE THREAD

**Issue by ShoupingShan** [tohhongxiang123/Gallery-Viewer#5]
你好，非常感谢您的工具，希望后期能够给album模块添加一个功能：
点击进入相应的文件夹后也可以对当前文件夹的图片选择Carousel和List可视化功能，而不是只有images下面的图片才可以自由选择。以及每个页面设置显示图品数和翻页功能，减少图片加载时间。

**Comment by tohhongxiang** [comment]
Done
